FROM debian:stretch-slim

RUN apt-get update && apt-get install -y wget git curl g++ gcc 
WORKDIR /root
# RUN curl https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_linux.tar.gz --output fbx202021_fbxsdk_linux.tar.gz
# RUN ls
# RUN tar -xvf fbx202021_fbxsdk_linux.tar.gz